### ISSUE TITLE
Images in a surface are low resolution.

### ISSUE THREAD

**Issue by h0tw1r3** [mickelson/attract#104]
I'm creating a generic vertical layout, in the process I wanted to flip-x (mirror) some artwork. Currently the only way to do that is by putting the artwork inside a surface.

My monitor resolution is 1200x1600.
I'd like to use a layout width/height of 480x640 for simplicity, and attract mode scales everything for me automatically - awesome.

Quality loss is particularly noticable because I recompiled with setSmooth( false ) to illustrate the resolution loss / gain.

fe.layout.width/height 480x640 (marquee and wheel images inside surface):

![screenshot from 2015-01-20 11 53 24](https://cloud.githubusercontent.com/assets/809115/5822599/12da209e-a09b-11e4-8b73-1c095f8a133d.png)

fe.layout.width/height 1200x1600 (marquee and wheel images inside surface):

![screenshot from 2015-01-20 11 52 32](https://cloud.githubusercontent.com/assets/809115/5822594/027ed0a0-a09b-11e4-9ec6-5dd7d3081b01.png)

fe.layout.width/height 480x640 (marquee and wheel images NOT in a surface):

![screenshot from 2015-01-20 12 02 12](https://cloud.githubusercontent.com/assets/809115/5822746/3210554a-a09c-11e4-9918-964d85ae1ec0.png)

I was expecting that scaling would automatically work for surfaces in the same way as the "primary" surface (fe).

Would making FeSurfaceTexture aware of the layout to actual resolution ratio fix the problem somehow?

**Comment by mickelson** [comment]
You could try creating the surface with a higher resolution to not lose scaling quality.

Also I think you can flip images without using a surface.  You just have to set the sub image when you actually have an image loaded in the artwork which can be a bit tricky (I think you would have to do it during the FromOldSelection transition event, since you would be able to get the texture width and texture height of the image at that point).

**Comment by h0tw1r3** [comment]
Thanks for the info on sub image.  May come in handy.

Makes sense that I must calculate a higher resolution for the surface.
