### ISSUE TITLE
Text Variable Filenames for Artwork/Images

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#130]
If I am not mistaken, right now artwork paths only look for files in the path by the full title.

Someone was trying to add manufacturer images into their layout, and I realized this could be much simpler if you could specify dynamic text variables for the artwork paths. This would allow you to customize the filenames AM looks up by using text variables (like text objects can), and you could even use prefixes or suffixes.

Example:
Artwork
   Name: Manufacturer
   Path: C:\Media\Manufacturers
   Filename Label (optional): [Manufacturer]

This would allow for Manufacturer images by looking in that path for Acclaim.png, Rare.png, Midway.png, Namco.png, etc...

Example 2:
Artwork
   Name: AMGraphics
   Path: C:\Media\AM
   Filename Label (optional): [DisplayName]-[FilterName]

This would allow custom graphics for each display/filter: mame-favourites.png, snes-usa.png, etc..

Example 3:
Artwork
   Name: Controls
   Path: C:\Media\Controls
   Filename Label (optional): [Control]

This would allow custom graphics for control types: joystick.png, lightgun.png, trackball.png, etc..

Ideally, this would also work for images, avoiding every users from having to configure custom artwork paths for one-off scenarios or included customized layout graphics..

fe.add_image("[Manufacturer].png", 0, 0, 150, 150);

This actually could resolve the following ticket as well:
https://github.com/mickelson/attract/issues/119

**Comment by mickelson** [comment]
Ok, this is implemented now with the linked commit.  You can specify magic tokens when adding images as suggested... so fe.add_image( "manufacturers/[Manufacturer].png", 0, 0, 150, 150 ); will display the image matching the manufacturer name that is in the "manufacturers" directory of the layout.

You can also do some pretty tricky stuff since this sort of thing can be used to call functions in squirrel as well... so fe.add_image( "manufacturer/[!get_manu].png", 0, 0 ) will call the get_manu() function in squirrel, which can return whatever string you want to have substituted...
