### ISSUE TITLE
Scraper ignores configured art directories.

### ISSUE THREAD

**Issue by elsonrodriguez** [mickelson/attract#174]
The scraper seems to always download to a hard-coded directory, even if directories are configured for flyer, snap, etc.

It'd be great if it compared/downloaded based on the configured directories.

**Comment by mickelson** [comment]
This is intentional.

The scraper checks the configured directories for artwork, and if there isn't any for a particular game only then does it try to scrape it (at least that is the way it is meant to work!).

Scraped artworks are kept in the attract-mode config directory so they don't mess with people's artwork collections and also to avoid some other potential problems.  You can always specify the location of the attract-mode config directory at the command line.

**Comment by elsonrodriguez** [comment]
Confirmed, working as designed.

I'm populating with an external utility first, and then using attract's scraper to fill in the blanks. The separate directories makes sense since external utilities might have strong opinions.

Go ahead and close, this hybrid approach is great.
