### ISSUE TITLE
Extreme slowdown when controller reconnected

### ISSUE THREAD

**Issue by zerojay** [mickelson/attract#210]
Using a personally compiled version of SFML/Attract 2.0 RC3 on a Raspberry Pi 3 running Retropie. Everything at latest git code changes. 

I have a controller with a short in the cable. Sometimes, depending on the angle I hold the controller, it may appear to be disconnected. If attract is started up with a USB controller plugged in, and then the controller disconnects for any reason - whether in-game or at attract itself - and then that controller is plugged back in, attract slows down to an absolute crawl with maybe a frame or two displayed per second while it spews out "Failed to flush inotify of all pending joystick events." to the console repeatedly. The only ways to get attract performing correctly again is either to disconnect the controller and leave it disconnected or quit and restart attract.

**Comment by mickelson** [comment]
I'm pretty sure this is due to the custom version of SFML that is being used by Attract-Mode on the RPi.  It's not keeping up with SFML development.

It looks like this issue has been fixed in SFML upstream, it's just a matter of porting the fixes in src/SFML/Window/Unix/JoystickImpl.cpp into the RPI branch of SFML....

https://github.com/SFML/SFML/commit/bbfef72fc635fefff7de4230a12a516f3264dd19

**Comment by mickelson** [comment]
Hi there, could you try out the version of sfml available here: https://github.com/mickelson/sfml-pi

and see if that fixes this?

**Comment by mickelson** [comment]
Closing as it is expected that the new version of SFML fixes this.
