### ISSUE TITLE
FEATURE:Seperate Game list Navigation from Menu Navigation 

### ISSUE THREAD

**Issue by ArcadeBliss** [mickelson/attract#216]
use case: when using a horizontal game list, it would be great to move the joystick left and right to navigate the list; however,  continue to use up and down to navigate an open menu. 

This would help the user experience when using attractmode. 

Also,  when it is a vertical game list,  the list navigation keys and menu navigation keys should be allowed to be identical. Let me know what you think.

**Comment by mickelson** [comment]
Yes, I agree it is a good idea to separate these, and to maybe rethink some of the other basic elements of the UI design.

One approach would be to simply decouple the gamelist navigation from menu navigation, and have it so the user can map each of those things separately...

**Comment by ArcadeBliss** [comment]
I think the other UI design is fine. mabye a few more custom fields and allow the custom fields. I would have seperated it myself however my C is veeeerrrryyyy rusty. I was unable to find where the appropriate changes should be in the src.

Thanks for listening.

**Comment by liquid8d** [comment]
I am of the opinion that AM should follow standard input of "left, right, up, down, select, back". Since layouts won't necessarily use up/down to navigate anyways and it is touted as a joystick/gamepad friendly FE :)

I'd suggest adding left/right, although i have just remapped page up/page down to be a left and right in code before.

At this point, the layout would determine if up/down or left/right (or all 4 would navigate) by catching the signals to handle it

**Comment by mickelson** [comment]
Agreed, and I am working on exactly this atm.

**Comment by mickelson** [comment]
Closing since this is implemented now in the master development branch.
