### ISSUE TITLE
preserve_aspect_ratio = true with Windowed mode

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#221]
When in windowed mode (Windows), fe.layout.preserve_aspect_ratio = true works when AM initially starts, but I don't think it adjusts adjust when window is resized, it appears as though it is stretching after that.

**Comment by liquid8d** [comment]
I'm not sure if it is stretched or maybe not the logic I was expecting. With my PreserveArt module, I have it where "fit" is based on the aspect ratio of the surface and the texture - in this case the window and the layout surface. So logic I would expect is something like:

[code]
local aspect = window.width / window.height.tofloat();
local layout_aspect = fe.layout.width / fe.layout.height.tofloat();
if ( aspect > 1.0 )
{
   //window is wide aspect
   if ( layout_aspect > 1.0 )
   {
      //layout is wide aspect
      if ( fe.layout.height > window.height )
      {
         //adjust aspect based on height
      } else
      {
         //adjust aspect based on width
      }
   } else
   {
      //layout is tall aspect
      //....
   }
} else
{
   //window is tall aspect
   if ( layout_aspect > 1.0 )
   {
      //layout is wide aspect
      //...
   } else
   {
      //layout is tall aspect
      //...
   }
}
[/code]

**Comment by mickelson** [comment]
I can confirm that there is no logic in there to handle the aspect ratio when in a window.  Attract-Mode simply continues on as though its dimensions are the full screen dimensions.

("window mode" really has just been hacked in there because it was requested at some point.  The frontend has been designed on the assumption that it is a full screen app)
