### ISSUE TITLE
FadeArt not cycling multiple artworks

### ISSUE THREAD

**Issue by keilmillerjr** [mickelson/attract#227]
https://github.com/mickelson/attract/blob/master/config/modules/fade.nut

```
//
// FadeArt - creates an artwork that does a smooth fade from existing to
// new when it changes images.  This artwork also cycles the image that is
// displayed when multiple artworks are available for a particular game.
//
```

I have marquee artwork with two paths. The FadeArt works as expected, except for a timed fade into the second art path (if available). Is anyone else experiencing this?

**Comment by mickelson** [comment]
Ok, this should be fixed now when artwork is matched across multiple paths.

**Comment by rsn8887** [comment]
Is it possible to make the random selection of artwork that is matched across multiple paths optional?

If turned off, AM should use look in the first configured folder at first and only if no artwork is found should it then continue to look in the second folder and so on.

For example I have set up multiple artwork folders, the first one being 2D box art, then 3D box art, then title screenshots etc. It would be great to revert back to the old behavior because then AM would only display title screen artwork if there is neither 3D nor 2D boxart available, instead of randomly picking from all available.

**Comment by keilmillerjr** [comment]
Issue was closed, but never resolved. I can probably figure out how to modify fade.nut to take two types of configured artworks and work as intended, but it will be a few weeks due to my current living situation.

**Comment by mickelson** [comment]
This has recently been changed again in the dev repository:  https://github.com/mickelson/attract/commit/b23c88141cc52e8bc75b07a1b668c35fa50fd69f

fade should randomize across all matched artwork from all configured paths.  Note that only art at the same level of the "selection order" (see readme.md) gets returned.

Hopefully this ome fixes this!
