### ISSUE TITLE
(Feature Request) Sub menus to the display menu

### ISSUE THREAD

**Issue by calle81** [mickelson/attract#347]
Hi,

Probably the most requested feature on the various Facebook forums for Attract Mode is the ability to have sub menus to the main menu. There is a huge community out there building themes and creating collections for Attract Mode but its hard to navigate the main menu when there is no way to add a sub menu. Eg: Arcade Collections -> Taito Classics, Konami classics, 80's Collection, 90's Collection etc.

The best solution would be if it was possible to have a limitless amount of submenus to make it as flexible as possible Eg: Handhelds -> Gameboy Advance -> Konami etc.

Kind regards,
Carl

**Comment by jolny** [comment]
This is relevant to my interests!

**Comment by fastlowrex** [comment]
In my opinion this is one of the next must haves for attract mode on retropie. I currently have 350 display wheels. Being able to sort these wheels in a hierarchy would be a massive improvement to navigation.

**Comment by rridenour** [comment]
Totally agree I would love sub menu hierarchy to sort through the wheels better

**Comment by bermonch** [comment]
I also agree with this.it needs submenú for better management

**Comment by SuperMagicom** [comment]
This would be a game changer for sure.

**Comment by l0ck0x** [comment]
sin esa opción el proyecto pierde muchisimos puntos respecto a otros como MALA :(

**Comment by fbs777** [comment]
Its possible to make menu + sub menus using wheels + text.  If you have creativity enough you can make a better layout design than hyperspin right now...

**Comment by calle81** [comment]
Hi @mickelson , it would be awesome if you could let us know if this feature is something you would consider adding. 

Keep up the amazing work! :)

**Comment by iameddysmith** [comment]
This is now a possibility. See attract mode forum for post!!

**Comment by bermonch** [comment]
Thanks for all mateEnviado desde mi Huawei-------- Mensaje original --------Asunto: Re: [mickelson/attract] (Feature Request) Sub menus to the display menu (#347)De: iameddysmith Para: mickelson/attract CC: bermonch ,Comment This is now a possibility. See attract mode forum for post!!

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mickelson/attract","title":"mickelson/attract","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mickelson/attract"}},"updates":{"snippets":[{"icon":"PERSON","message":"@iameddysmith in #347: This is now a possibility. See attract mode forum for post!!"}],"action":{"name":"View Issue","url":"https://github.com/mickelson/attract/issues/347#issuecomment-319580970"}}}

**Comment by mickelson** [comment]
Hi, there have been various recent changes to the frontend that now allow you to create any number of submenus...

You can now create menu entries that act as shortcuts to other "Displays": https://github.com/mickelson/attract/commit/0ba69c42f3e9d7789dd68ed164fecf882e4be787

There are also changes for shortcut navigation and multiple menu levels: https://github.com/mickelson/attract/commit/b71b0e48c478a115a9648968701b6191f831e23e

Menu shortcuts can also be editted using the "edit game" function: https://github.com/mickelson/attract/commit/aa2d716aada8b243c938322a9eb8ccf2bd2dd947

**Comment by bermonch** [comment]
Ok thanks mate,great job by the way.i love your frontenis.then,if i update
the versión,Will i have avaible this changes?
Thanks regards

**Comment by calle81** [comment]
Great job, can’t wait to try it out! ☺

Kind regards,
Carl
Från: Andrew Mickelson [mailto:notifications@github.com]
Skickat: den 15 oktober 2017 21:38
Till: mickelson/attract <attract@noreply.github.com>
Kopia: Carl Hagström - Nitma <carl.h@nitma.se>; Author <author@noreply.github.com>
Ämne: Re: [mickelson/attract] (Feature Request) Sub menus to the display menu (#347)


Hi, there have been various recent changes to the frontend that now allow you to create any number of submenus...

You can now create menu entries that act as shortcuts to other "Displays": 0ba69c4<https://github.com/mickelson/attract/commit/0ba69c42f3e9d7789dd68ed164fecf882e4be787>

There are also changes for shortcut navigation and multiple menu levels: b71b0e4<https://github.com/mickelson/attract/commit/b71b0e48c478a115a9648968701b6191f831e23e>

Menu shortcuts can also be editted using the "edit game" function: aa2d716<https://github.com/mickelson/attract/commit/aa2d716aada8b243c938322a9eb8ccf2bd2dd947>
