### ISSUE TITLE
Not Working With MAMEUI64

### ISSUE THREAD

**Issue by hassenpheffer** [mickelson/attract#386]
Hello!

I've posted about this before months ago but got no working solutions. Now with the latest version of AM I'm still having the same issue.

Here's the rub:

I run AM. Go into MAME and choose a game. It open MAMEUI64 up but doesn't open a game. It just sits there. Nothing. UI works but no game starts. I close MAMEUI64 and it goes back to AM.

I've tried everything. Set up. Uninstall and reinstall for both AM and MAMEUI64 and no changes.

I don't know what else to do.

HELP!

**Comment by estefan3112** [comment]
Hi,  why would you want to switch from Attract Mode into another User Interface? That does not seem to nake sense. All you need is MAME and set the commands in AM. Cheers!

**Comment by hassenpheffer** [comment]
That's not at all helpful.

**Comment by dabonetn** [comment]
What's your run command?

**Comment by hassenpheffer** [comment]
Where do I find that info?

**Comment by estefan3112** [comment]
http://forum.attractmode.org/index.php?topic=328.0
The forum is full of instructions, here is the basic guide. I also did a guide for Macs on my Blog.
As stated before, you want to start the mame64.exe file, not the User Interface. Since there seems to be no issue at all, I would suggest that you close the issue here - this is for development, the forum is for help by other users. I am quite sure that you will make it. Cheers!

**Comment by hassenpheffer** [comment]
I've done this. This is the third time in the past year that I've asked for help. I was given that link the first time I asked.

Nothing changed.

I'm starting to wonder if it's an issue with MAMEUI64 and not AM.
