### ISSUE TITLE
zorder is very unpredictable.

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#401]
When you run this layout 

```
local tiles = []
for (local i = 0; i < 10; i++)
{
	local obj = fe.add_text("txt", 100 * i, 0, 100, 100)
	obj.nomargin = true
	obj.charsize = 30
	obj.align = Align.Centre
	tiles.push(obj)
}

tiles[0].zorder = 100
tiles[9].zorder = 101

for (local i = 0; i < 10; i++)
{
	tiles[i].msg = tiles[i].zorder
}
```

a common sense makes you believe that the result on the screen will be 
100  1  2  3  4  5  6  7  8  101

but instead you get:
8  0  1  2  3  4  5  6  7  9

AM should allow in my opinion to set zorder greater that the number of total drawable elements.
At the current state the whole zorder table behaves very unpredictable as it gets shifted every time you modify some zorder value.
When I set the zorder of an object I wish it stays the same.

**Comment by oomek** [comment]
One more thing. In case when zorder has the same values the elements should be drawn in the order they have been initialised.

**Comment by liquid8d** [comment]
@mickelson explained this to me here:

https://github.com/mickelson/attract/issues/353

Using zorder just bumps that object up in the draw list, but I agree - we need to have better control of zorder for it to be useful.

Typical use case for zorder would be to temporarily bring an object to the front, then return it to where it was. You can't really do this without defining zorders for every single object, which becomes a pain. Ideally, we want to use zorder just like zindex for css - everything draws in order of creation - unless it has a set zorder, in which case it inserts itself in that position. Meaning everything has 0 zorder, but if multiple objects have 1 - draw them above all 0's (BUT still in the order they were created).

If the draw list is just an array, rather than make zorder its position in the array - perhaps you can make zorder an attribute of the object. When rendering the draw list, draw objects in order they were created, looping through each zorder number. (hopefully that makes sense)

**Comment by oomek** [comment]
I’m happy that you agree that zorder function needs rewriting. For this moment i’ve overome it by specifying the zorder=9999 for the objects I need in front in tick function including my custom overlay elements. It works but I hipe it does not bring any penalties in performance.

**Comment by mickelson** [comment]
Ok I'm game for changing how zorder works. The only pain is that this change will inevitably break people's existing layouts, so I want to make sure it is right the first time so that any breaks only have to be fixed once.  So here is what I propose (which can be implemented fairly easily):

- zorder can be set to any positive or negative integer value.  the zorder will be an attribute that stays at whatever value is set
- lower zorders are drawn first
- default zorder is 0
- objects with the same zorder will preserve their relative ordering.  So when an object is first added, it will be the last object at zorder '0' that gets drawn.  If its zorder is set to -1 and then back to 0, it will become the first object at zorder '0' that is drawn.  If its zorder is set to 1 and then back to 0, it will become the last object at zorder '0' that is drawn... 

thoughts?

**Comment by oomek** [comment]
Sounds logical and functional to me

**Comment by mickelson** [comment]
Pull request with proposed changes: https://github.com/mickelson/attract/pull/408
