### ISSUE TITLE
issue #459 Solved?

### ISSUE THREAD

**Issue by zlagos** [mickelson/attract#476]
Announcemente 2.4.1 says:

* Issue #459 - fixed listbox selection background fading/colour setting

This layout with 2.4.1 version:

//----------------------------------------
fe.load_module("animate");

local flx = fe.layout.width;
local fly = fe.layout.height;
local flw = fe.layout.width;
local flh = fe.layout.height;

my_time <- 600;
my_delay <- 3500;

// Listbox
::OBJECTS <- {lbx = fe.add_listbox(flx*0.76, fly*0.33, flw*0.20, flh*0.64)}
OBJECTS.lbx.rows = 21;
OBJECTS.lbx.charsize = 24;
OBJECTS.lbx.align = Align.Left;
OBJECTS.lbx.bg_alpha = 0;
OBJECTS.lbx.set_rgb(255,255,255);
OBJECTS.lbx.selbg_alpha = 0;
OBJECTS.lbx.set_sel_rgb(255,0,0);
OBJECTS.lbx.sel_alpha = 255;

local move_lbx3 = {when = Transition.ToNewSelection, property = "alpha", start = 0, end = 255, time = 1}  
local move_lbx4 = {when = When.ToNewSelection, property = "alpha", start = 255, end = 0, time = my_time, delay = my_delay}  
animation.add(PropertyAnimation(OBJECTS.lbx, move_lbx3));
animation.add(PropertyAnimation(OBJECTS.lbx, move_lbx4));
//-----------------------------------------------------

Has this result:

https://www.youtube.com/watch?v=Z4vmmwdcFps

I do not see that the bug has been fixed.

**Comment by oomek** [comment]
The previous bahaviour of the Animate module was most likely caused by a loophole in Attract Mode. If you need to animate all 4 alpha properties of the ListBox object I suggest you to do it as follows:

`fe.load_module("animate")

local flx = fe.layout.width
local fly = fe.layout.height
local flw = fe.layout.width
local flh = fe.layout.height

my_time <- 600
my_delay <- 1000

// Listbox
::OBJECTS <- {lbx = fe.add_listbox(flx*0.76, fly*0.33, flw*0.20, flh*0.64)}
OBJECTS.lbx.rows = 21
OBJECTS.lbx.charsize = 24
OBJECTS.lbx.align = Align.Left

OBJECTS.lbx.alpha = 255
OBJECTS.lbx.set_rgb(255,255,255)

OBJECTS.lbx.bg_alpha = 255
OBJECTS.lbx.set_bg_rgb(50,50,50)

OBJECTS.lbx.set_sel_rgb(255,0,0)
OBJECTS.lbx.sel_alpha = 255

OBJECTS.lbx.set_selbg_rgb(100,100,100)
OBJECTS.lbx.selbg_alpha = 255


local fadein_alpha_lbx = {when = Transition.ToNewSelection, property = "alpha", start = 255, end = 255, time = 1}
local fadein_bg_alpha_lbx = {when = Transition.ToNewSelection, property = "bg_alpha", start = 255, end = 255, time = 1}
local fadein_sel_alpha_lbx = {when = Transition.ToNewSelection, property = "sel_alpha", start = 255, end = 255, time = 1}
local fadein_selbg_alpha_lbx = {when = Transition.ToNewSelection, property = "selbg_alpha", start = 255, end = 255, time = 1}

local fadeout_alpha_lbx = {when = When.ToNewSelection, property = "alpha", start = 255, end = 0, time = my_time, delay = my_delay}
local fadeout_bg_alpha_lbx = {when = When.ToNewSelection, property = "bg_alpha", start = 255, end = 0, time = my_time, delay = my_delay}
local fadeout_sel_alpha_lbx = {when = When.ToNewSelection, property = "sel_alpha", start = 255, end = 0, time = my_time, delay = my_delay}
local fadeout_selbg_alpha_lbx = {when = When.ToNewSelection, property = "selbg_alpha", start = 255, end = 0, time = my_time, delay = my_delay}

animation.add(PropertyAnimation(OBJECTS.lbx, fadein_alpha_lbx));
animation.add(PropertyAnimation(OBJECTS.lbx, fadein_bg_alpha_lbx));
animation.add(PropertyAnimation(OBJECTS.lbx, fadein_sel_alpha_lbx));
animation.add(PropertyAnimation(OBJECTS.lbx, fadein_selbg_alpha_lbx));

animation.add(PropertyAnimation(OBJECTS.lbx, fadeout_alpha_lbx));
animation.add(PropertyAnimation(OBJECTS.lbx, fadeout_bg_alpha_lbx));
animation.add(PropertyAnimation(OBJECTS.lbx, fadeout_sel_alpha_lbx));
animation.add(PropertyAnimation(OBJECTS.lbx, fadeout_selbg_alpha_lbx));
`

**Comment by zlagos** [comment]
Thanks, work perfectly.
