### ISSUE TITLE
Lack of communication

### ISSUE THREAD

**Issue by keilmillerjr** [mickelson/attract#622]
I spent 3.5 years on an open PR without a comment. Spent multiple times trying to get ahold of @mickelson. I noticed a few of @oomek PR's were just accepted. I would like to contribute as well as others. However, none of us can even get a comment. Please respond here or hop on discord!

https://github.com/mickelson/attract/pull/291

**Comment by mickelson** [comment]
Hi there, its not intentional, I miss a lot of things on here as I’m just one person with very limited time for this project.

**Comment by keilmillerjr** [comment]
Perhaps appointing a maintainer would help? Communication is important in an open source project. It would help spread out responsibilities.

**Comment by oomek** [comment]
I also support this idea. If you're afraid of merging experimental features with the `master` there is always an option to create a `beta` branch and merging it with the `master` after testing phase has completed.

**Comment by calle81** [comment]
That sounds like a great idea keil and oomek :)

**Comment by keilmillerjr** [comment]
@mickelson Thoughts about adding a maintainer? @zpaolo11x just implemented a feature in his layout to auto update. His layout should be on here. If there was constant updates to this git repo, including really good layouts, then we can implement things like snap or brew packages to keep people up to date? Would like some input from you when you have time. Right now it's a one man show on attract.

**Comment by Yaron2019** [comment]
@mickelson Hi Andrew, my name is Yaron and in the last few months I have developed a large collection of pretty popular themes for Attract Mode (88 themes to be exact). Like keilmillerjr and Oomek I also think that it will be a good idea to appoint a maintainer for the project. A beta branch is also a very good idea actually. Attract Mode has a capable community with some very passionate developers that can contribute much more.

**Comment by mickelson** [comment]
Hi yes this sounds like a good idea to me.  Making a dev branch or beta branch or whatever and allowing others to check changed to the code into it make sense to me.

I think the best way forward may be to separate attract mode into two repositories... one for the core program source code and another for the broader package with all of its layouts/intro videos/etc. and all the binary files that go along with that.  I really want to avoid having large binaries in the source code repository because that will bog down git over time since a full copy of every binary version is retained in  the history.

So I'd like to figure out the best way to separate the attract-mode package into a "code" repository (for the core program) and a "package" repo for the broader package.  Once that is figured out, I'd be happy to hand of maintenance of the "package" repo to someone who is interested in implementing and managing the features you mention @keilmillerjr (good layouts, a package system, etc)...  There would be the beta branch for the core code as well.  I'd like to keep control over merging into master for the core program for now.

**Comment by keilmillerjr** [comment]
@mickelson could separate as such: attract/attract, attract/extras (module/layout/plugin), attract/wiki. I did similar thing with fork on gitlab. See the [wiki](https://attractmode.gitlab.io/wiki/) that could use community involvement to improve. Can use permissions within the group to restrict access.

I am looking into snapcraft and willing to take on task. Perhaps it would be a good way to distribute to Linux users. Thoughts? It would eliminate github equivalent of artifacts for linux. I haven't looked into Windows, but there is Chocolatey and microsoft new windows package manager.?

**Comment by Yaron2019** [comment]
@mickelson that will be the best solution in my opinion as well.
