### ISSUE TITLE
Request for a new release (2.6.3)

### ISSUE THREAD

**Issue by mbarnes** [mickelson/attract#743]
Just requesting a new release tag, since it's been over a year since 2.6.2 was released.

Looks to me like there's been enough changes since 2.6.2 to warrant a 2.6.3.

**Comment by mickelson** [comment]
makes sense to me. It might be 2.7 as I think there are definitely some new features.AndrewOn Jun 7, 2023, at 9:30 AM, Matthew Barnes ***@***.***> wrote:﻿
Just requesting a new release tag, since it's been over a year since 2.6.2 was released.
Looks to me like there's been enough changes since 2.6.2 to warrant a 2.6.3.

**Comment by mbarnes** [comment]
Thanks for the release tag.
https://github.com/mickelson/attract/releases/tag/v2.7.0
