### ISSUE TITLE
Won't map X-Arcade's player one joystick. 

### ISSUE THREAD

**Issue by orsty3001** [mickelson/attract#95]
It will let me map all the buttons but ignores the joystick. I noticed that the player one joystick when pushed up maps in mame to "NUM_8". So I'm assuming Attract-Mode doesn't know what to do with the input from a number pad on a keyboard.

**Comment by Emerica** [comment]
Having the same issue here in Ubuntu 14.04
I have a Ipaq that was configured in windows to use the number pad for the second controller.
Setting the controls in mame itself works fine so I know the inputs work.
It would be nice for this to work rather than have to reconfigure the ipaq under Windows again.
Had this been looked at at all? I'm guessing at the age of the bug that there may be a (higher than mame level) keyboard api not returning those events and it might be more trouble than it's worth to fix? Or would this just be a list of missing inputs to look for?
I'll have to dig into that once free time allows. Input appreciated.

**Comment by mickelson** [comment]
Hi,

I just took a look at this one.  It looks like a bug in SFML...  I've submitted a patch upstream to fix it:

https://github.com/SFML/SFML/pull/910

**Comment by Emerica** [comment]
You rock, thank you.

**Comment by mickelson** [comment]
The patch fixing this has been accepted upstream, so the fix is in the next version of SFML
